#!/bin/bash
# vimntu - quick install of plugins and distributions i find useful
# author: Adam Stokes <adam.stokes@ubuntu.com>
###############################################################################

set -eux

VIMRCPATH=${HOME}/.vimrc.after
GVIMRCPATH=${HOME}/.gvimrc.after
JANUSPATH=${HOME}/.janus

if [[ ! -d ${JANUSPATH} ]]; then
  mkdir -p ${JANUSPATH}
fi

# VIMRC config
VIMRCAFTER=$(cat <<EOF
color jellybeans
set textwidth=79
set formatoptions=qrn1
if exists('+colorcolumn')
  set colorcolumn=80
endif
set list
set listchars=tab:.\ ,trail:.,extends:#,nbsp:.
set numberwidth=5
set cursorline
set cursorcolumn
EOF
)

# GVIMRC config
GVIMRCAFTER=$(cat <<EOF
color jellybeans
if has("gui_running")
  set guifont=Monospace\ 10
  set list
  set listchars=tab:▸\ ,eol:¬,extends:#,nbsp:.,trail:.
  set guioptions-=r
  set go-=L
  set go-=T
endif
EOF
)

install_pkgs() {
  let RET=0
  let packages=(vim \
    vim-gtk \
    git \
    ctags \
    ruby1.9.1 \
    rake
  )
  sudo apt-get update -y

  # only install packages we need
  for i in "${packages[@]}"
  do
    RET=$(dpkg -l ${i})
    if [ ${RET} -eq 1 ]; then
      sudo apt-get -y ${i}
    fi
  done
}

install_janus() {
  if [ -d ${JANUSPATH} ]; then
    # janus already installed, update instead
    cd ${JANUSPATH} && git pull && return
  fi
  if [ -x /usr/bin/curl ]; then
    curl -Lo- https://bit.ly/janus-bootstrap | bash
  elif [ -x /usr/bin/wget ]; then
    wget --no-check-certificate https://bit.ly/janus-bootstrap -O - | bash
  else
    echo "No curl/wget found, install with apt-get install curl"
    return 1
  fi
}

install_git_pkgs() {
  let packages=(
    git://github.com/antono/html.vim \
    git://github.com/bling/vim-airline \
    git://github.com/klen/python-mode \
    git://github.com/nanotech/jellybeans.vim \
    git://github.com/othree/html5.vim \
    git://github.com/rodjek/vim-puppet \
    git://github.com/sickill/vim-pasta \
    git://github.com/tpope/vim-bundler \
    git://github.com/tpope/vim-endwise \
    git://github.com/tpope/vim-eunuch \
    git://github.com/tpope/vim-fugitive \
    git://github.com/tpope/vim-haml \
    git://github.com/tpope/vim-rails \
    git://github.com/tpope/vim-scriptease \
    git://github.com/tpope/vim-sensible \
    git://github.com/tpope/vim-surround \
    git://github.com/vimoutliner/vimoutliner \
    git://github.com/vim-perl/vim-perl \
    git://github.com/vim-ruby/vim-ruby \
    git://github.com/Yggdroot/indentLine \
    git://github.com/yko/mojo.vim \
    git://github.com/digitaltoad/vim-jade \
    git@github.com:wavded/vim-stylus
  )
  for i in "${packages[@]}"
  do
    # only if url ends with .git
    # _dir="${i##*/}"
    if [ -d ${i} ]; then
      cd ${JANUSPATH}/${i} && git pull
    else
      cd ${JANUSPATH} && git clone ${i}
    fi
  done
}

install_pkgs
install_janus
install_git_pkgs

exit $?
